// 전역 CSS 파일 import - Tailwind CSS와 커스텀 스타일 포함
import './globals.css'

// Next.js 메타데이터 설정 - SEO와 브라우저 탭 제목에 사용
export const metadata = {
  title: '포트폴리오 페이지', // 브라우저 탭에 표시될 제목
  description: 'Generated by create next app', // 페이지 설명 (SEO용)
}

// 루트 레이아웃 컴포넌트 - 모든 페이지의 기본 구조
export default function RootLayout({ children }) {
  // children: 각 페이지의 내용이 들어올 props
  return (
    // HTML 루트 요소
    <html>
      {/* body 요소 - 최소 높이 전체 화면, 텍스트 색상 흰색 */}
      <body className="min-h-screen text-white">
        {/* children 렌더링 - 각 페이지의 내용이 여기에 표시됨 */}
        {children}
      </body>
    </html>
  )
}
